# Site settings
title: Bloom
email: directors@bloom.org.au
description: > # this means to ignore newlines until "baseurl:"
  Profectus helps young Western Australian entrepreneurs grow and achieve their potential.
paginate: 5
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bloom.org.au" # the base hostname & protocol for your site
twitter_username: bloom_labs
github_username:  bloomlabs
facebook_username: ProfectusAustralia
# pinterest_username: bloomlabs
instagram_username: bloom_lab
youtube_link: https://www.youtube.com/channel/UCX6mq8Spc6JlgfDnaNvMinQ/feed
logo_url:
# Build settings
markdown: kramdown
exclude:
  - "Gruntfile.js"
  - "Rakefile"
  - "node_modules"
  - "public"
  - "package.json"
gems:
  - jekyll-redirect-from  
